base_url = 'https://sable-20.github.io/'
default_language = 'en-us'
title = 'Sable Ayala | University Student'

math = true
theme = ["hugo-admonitions", "PaperMod"]
[pagination]
pagerSize = 5

[markup]
  [markup.goldmark]
  renderer.unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
ShowReadingTime = true
defaultTheme = "auto"
ShowShareButtons = true
env = "production"

[params.assets]
disableHLJS = true

[markup.highlight]
codeFences = true
guessSyntax = false
lineNos = true
lineNumbersInTable = true
tabWidth = 4
style = 'catppuccin-frappe'

[params.profileMode]
enabled = true
title = "Sable Ayala"
subtitle = "Just another university student making their way through life."
imageUrl = "https://avatars.githubusercontent.com/u/72171476?v=4"
imageWidth = 120
imageHeight = 120
[[params.profileMode.buttons]]
name = "Archive"
url = "/archive"
[[params.socialIcons]]
name = "github"
url = "https://github.com/Sable-20"

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 30

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "example"
name = "home"
url = "/"
weight = 10

[[menu.main]]
identifier = "about"
name = "about me"
url = "/about"
weight = 30

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "rss"