baseURL = 'https://sable-20.github.io'
languageCode = 'en-us'
title = 'Sable Ayala'
defaultcontentlanguage = 'en'
noClasses = true

[caches]
[caches.images]
dir = ":cacheDir/images"

[module]
[[module.imports]]
path = 'github.com/luizdepra/hugo-coder'

theme = 'hugo-coder'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[pagination]
pagerSize = 20

[markup.highlight]
style = 'catppuccin-frappe'

[params]
author = "Sable Ayala"
info = "Student | Pharmacy Technician"
description = "My personal website and my resume"
keywords = "blog,resume,pharmacy,student"
avatarurl = 'https://avatars.githubusercontent.com/u/72171476?v=4'

since = '2025'

enableTwemoji = true
colorScheme = "auto"
hidecolorschemetoggle = false

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/Sable-20"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/sable-ayala/"

[languages.en]
languageName = "🇺🇸"

[[languages.en.menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"

[[languages.en.menu.main]]
name = "Resume"
weight = 3
url = "resume/"

[languages.fr]
languageName = "🇫🇷"
title = "Sable Ayala"

[languages.fr.params]
author = "Sable Ayala"
info = "étudiante ◊ étudiante de l'informatique"
description = "Mon site personnel et CV"

[[languages.fr.menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[languages.fr.menu.main]]
name = "À propos'"
weight = 2
url = "about/"

[[languages.fr.menu.main]]
name = "CV"
weight = 3
url = "resume/"

[languages.ar]
languageName = "🇵🇸"
title = "Sable Ayala"

[languages.ar.params]
author = "Sable Ayala"
info = "طالب إ طاليب علم الحاسب"
description = "موقعي الشخصي وسيرتي الذاتية"

[[languages.ar.menu.main]]
name = "المدونة"
weight = 1
url = "posts/"

[[languages.ar.menu.main]]
name = "عني"
weight = 2
url = "about/"

[[languages.ar.menu.main]]
name = "سيرة ذاتية"
weight = 3
url = "resume/"
