title = "Sable Ayala - University Student"
baseURL = "https://sable-20.github.io"
languageCode = "en-US"
theme = "osprey-delight-custom"
tags = [ "personal", "homepage", "portfolio" ]
disableKinds = [ "taxonomy" ]
enableEmoji = true
pygmentsUseClasses = true

[[module.imports]]
path = "github.com/Sable-20/Sable-20.github.io"

[Params]
description = "University student's site"
logoBig = "osprey-delight.png"
logoSmall = "favicon.png"
opengraphImage = "/images/osprey-delight.png"
favicon = "favicon.png"
theme = "dedark"
mdTagline = """
# Welcome!
 ## My name is Sable Ayala{cursor}"""
enforceSinglePage = false
copyright = true

  [Params.author]
  name = "Sable Ayala"

  [[Params.Social]]
  type = "twitter"
  url = ""

  [[Params.Social]]
  type = "linkedin"
  url = ""

  [[Params.Social]]
  type = "github"
  url = "https://github.com/Sable-20/"

  # [[Params.Social]]
  # type = "heart"
  # url = "https://github.com/sponsors/kdevo"

  # [[Params.Social]]
  # type = "stackoverflow"
  # url = ""

  [[Params.Social]]
  type = "spotify"
  url = "https://open.spotify.com/artist/5NhBOdJh6T1tgtM5Au1Opl"

  [Params.Feat]
  ajaxBasin = "https://usebasin.com/f/{YOUR-12-CHAR-FORM-KEY-HERE}"
  useStructuredData = true
  useTermynal = true
  googleTagManager = ""
  notifyOnNewThemeVersion = true

[Params.Image.Logo]
resize = "600x"

[Params.Image.Gallery]
resize = "600x"

[Params.Image.Background]
resize = "1920x"
resizeLQIP = "256x"

[[Menu.Main]]
name = "About"
identifier = "about"
url = "/about"
weight = 1

[[Menu.Main]]
name = "Work"
identifier = "gallery"
url = "/work"
weight = 2

[[Menu.Main]]
name = "Blog"
identifier = "blog"
url = "/blog"
weight = 3

[[Menu.Main]]
name = "Contact"
identifier = "contact"
url = "/contact"
weight = 4
